import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from "@/components/ui/theme-provider"
import Navbar from '@/components/ui/Navbar'; // Adjust the path to your Navbar component
import { SearchFilterProvider } from '@/context/SearchFilterContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Call Center',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main>
            <SearchFilterProvider>
              {children}
            </SearchFilterProvider>
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
